pipeline {
    agent any
    stages{
        stage('initialize'){
            steps{
                echo"initilizing the code file"
            }
        }
        stage('build'){
            steps{
                echo "hello world"
            }
        }
    }

}
